/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as YourFormsIndexImport } from './routes/your-forms/index'
import { Route as TemplatesIndexImport } from './routes/templates/index'
import { Route as AppIndexImport } from './routes/app/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const YourFormsIndexRoute = YourFormsIndexImport.update({
  id: '/your-forms/',
  path: '/your-forms/',
  getParentRoute: () => rootRoute,
} as any)

const TemplatesIndexRoute = TemplatesIndexImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof rootRoute
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesIndexImport
      parentRoute: typeof rootRoute
    }
    '/your-forms/': {
      id: '/your-forms/'
      path: '/your-forms'
      fullPath: '/your-forms'
      preLoaderRoute: typeof YourFormsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/your-forms': typeof YourFormsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/your-forms': typeof YourFormsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/app/': typeof AppIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/your-forms/': typeof YourFormsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app' | '/templates' | '/your-forms'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app' | '/templates' | '/your-forms'
  id: '__root__' | '/' | '/app/' | '/templates/' | '/your-forms/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppIndexRoute: typeof AppIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  YourFormsIndexRoute: typeof YourFormsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppIndexRoute: AppIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  YourFormsIndexRoute: YourFormsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/app/",
        "/templates/",
        "/your-forms/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/app/": {
      "filePath": "app/index.tsx"
    },
    "/templates/": {
      "filePath": "templates/index.tsx"
    },
    "/your-forms/": {
      "filePath": "your-forms/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
